Config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home_module.urls')),
    path("products/", include('product_module.urls')),
    path("contact-us/", include('contact_module.urls')),
    path("users/", include('user_module.urls')),
    path("blog/", include('blog_module.urls')),
    path('cart/', include('cart_module.urls')),
    path("about-us/", include('aboutus_module.urls')),
    path('user-panel/', include("user_dashboard_module.urls")),
    path("wish-list/", include("wish_module.urls")),
    path("asked-question/", include("questions_module.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_module/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', BlogListView.as_view(), name='blog-list'),
    path('blog/<id>/', BlogDetailView.as_view(), name='blog-detail'),
    path('send-comment/', send_comment)
]

blog_module/models.py
from django.db import models
from user_module.models import User


# Create your models here.

class BlogModel(models.Model):
    image = models.ImageField(upload_to='blog', verbose_name="تصویر")
    title = models.CharField(max_length=300, verbose_name="عنوان")
    text = models.TextField(verbose_name="متن")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, editable=False, verbose_name="کاربر")
    date = models.DateTimeField(null=True, verbose_name="تاریخ")
    visited = models.IntegerField(default=0, verbose_name="بازدید")
    is_active = models.BooleanField(default=True, verbose_name="منتشر")
    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


class CommentModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    parent = models.ForeignKey('CommentModel', on_delete=models.CASCADE, verbose_name='والد', null=True, blank=True)
    create = models.DateTimeField(auto_now_add=True, verbose_name="ایجاد شده در")
    text = models.TextField(verbose_name='متن کامنت')
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE, verbose_name='مقاله', db_index=True)
    is_publish = models.BooleanField(default=False, verbose_name='منتشر')
    def __str__(self):
        return self.user.username
    class Meta:
        verbose_name = 'کامنت مقاله'
        verbose_name_plural = 'کامنت های مقاله'

blog_module/views.py
from django.http import HttpRequest, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView
import logging
from pyexpat.errors import messages
from cart_module.models import CartModel
from product_module.models import ProductModel, ProductBrand
from .models import BlogModel, CommentModel

# Create your views here.
logger = logging.getLogger('blog_module')


def res_req(request):
    return JsonResponse({'status': 'success'})


class BlogListView(ListView):
    template_name = 'blog-list.html'
    model = BlogModel
    context_object_name = 'blogs'

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        context["blogs"] = BlogModel.objects.filter(is_active=True)
        user = self.request.user
        cart = CartModel.objects.filter(user_id=user.id, is_paid=False).first()
        context['cart'] = cart
        context['recent_blogs'] = BlogModel.objects.filter(is_active=True).order_by('-date')[:3]
        context['visited_products'] = ProductModel.objects.filter(is_active=True).order_by('-visited')[:3]
        context['discount_products'] = ProductModel.objects.filter(is_active=True).order_by('-discount')[:3]
        context['tags'] = ProductBrand.objects.all()
        return context


class BlogDetailView(View):
    def get(self, request: HttpRequest, id):
        try:
            blog = BlogModel.objects.filter(id=id).first()
            if blog:
                blog.visited += 1
                blog.save()
            comments_res = CommentModel.objects.filter(blog_id=blog.id, is_publish=True)
            comments = comments_res.filter(parent=None)
            user = request.user
            cart = CartModel.objects.filter(user_id=user.id, is_paid=False).first()
            return render(request, 'blog-detail.html', {
                'blog': blog,
                'comments': comments,
                'count_comment': len(comments_res),
                'cart': cart,
                'visited': blog.visited
            })
        except Exception as err:
            logger.debug(f'this error is : {err}')
            return render(request, '404.html')


def send_comment(request):
    text = request.GET.get("text")
    blog_id = int(request.GET.get("blog_id"))
    parent = request.GET.get("parent")
    if parent != 'false':
        new_comment = CommentModel.objects.create(user=request.user, text=text, blog_id=blog_id, parent_id=int(parent),
                                                  is_publish=True)
    else:
        new_comment = CommentModel.objects.create(user=request.user, text=text, blog_id=blog_id, parent=None,
                                                  is_publish=False)
    comments = CommentModel.objects.filter(blog_id=blog_id, is_publish=True)
    return render(request, 'comment-box.html', {
        'comments': comments,
        'count_comment': len(comments),
    })

blog_module/templates/comment-box.html
{% load poll_extras %}
<h4 class="title">{{ count_comment }} نظر</h4>
<ul class="comment-list">
    {% for comment in comments %}
        <!-- Start Single Comment  -->
        <li class="comment">
            <div class="comment-body">
                <div class="single-comment">
                    <div class="comment-inner">
                        <h6 class="commenter">
                            <a class="hover-flip-item-wrapper" href="#">
                                                            <span class="hover-flip-item">
                                                                <span data-text="{{ comment.user.first_name }} {{ comment.user.last_name }}">{{ comment.user.first_name }} {{ comment.user.last_name }}</span>
                                                            </span>
                            </a>
                        </h6>
                        <div class="comment-meta">
                            <div class="time-spent">{{ comment.create|j_date }}
                                در {{ comment.create|j_time|time }}</div>
                            <div class="reply-edit">
                                <div class="reply">
                                    <a class="comment-reply-link hover-flip-item-wrapper"
                                       onclick="set_parent({{ comment.id }})">
                                                                    <span class="hover-flip-item">
                                                                        <span data-text="Reply" style="cursor: pointer">پاسخ</span>
                                                                    </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="comment-text">
                            <p>{{ comment.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% for sub in comment.commentmodel_set.all %}
                {% if sub.is_publish %}
                    <ul class="children">
                        <!-- Start Single Comment  -->
                        <li class="comment">
                            <div class="comment-body">
                                <div class="single-comment">
                                    <div class="comment-inner">
                                        <h6 class="commenter">
                                            <a class="hover-flip-item-wrapper" href="#">
                                                                    <span class="hover-flip-item">
                                                                        <span data-text="Rahabi Khan">{{ sub.user.username }}</span>
                                                                    </span>
                                            </a>
                                        </h6>
                                        <div class="comment-meta">
                                            <div class="time-spent">{{ sub.create|j_date }}
                                                در {{ sub.create|j_time|time }}
                                            </div>
                                        </div>
                                        <div class="comment-text">
                                            <p>{{ sub.text }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <!-- End Single Comment  -->
                    </ul>
                {% endif %}
            {% endfor %}
        </li>
        <!-- End Single Comment  -->
    {% endfor %}

</ul>