Config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home_module.urls')),
    path("products/", include('product_module.urls')),
    path("contact-us/", include('contact_module.urls')),
    path("users/", include('user_module.urls')),
    path("blog/", include('blog_module.urls')),
    path('cart/', include('cart_module.urls')),
    path("about-us/", include('aboutus_module.urls')),
    path('user-panel/', include("user_dashboard_module.urls")),
    path("wish-list/", include("wish_module.urls")),
    path("asked-question/", include("questions_module.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wish_module/urls.py
from django.urls import path
from . import views
from .views import add_to_wish, delete_wish_detail

urlpatterns = [
    path('' , views.WishView.as_view(), name='wish'),
    path('add-to-wish/', add_to_wish, name='add_to_wish'),
    path('delete-wish-detail/', delete_wish_detail, name='delete_wish_detail'),
]

wish_module/models.py
from django.db import models
from product_module.models import ProductModel
from user_module.models import User


# Create your models here.

class WishModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    def __str__(self):
        return self.user.username
    class Meta:
        verbose_name = "علاقه مندی"
        verbose_name_plural = "علاقه مندی ها"

class WishDetailModel(models.Model):
    wish = models.ForeignKey(WishModel, on_delete=models.CASCADE, verbose_name='علاقه مندی')
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE, verbose_name='محصول')
    def __str__(self):
        return f'{self.product.title} - {self.wish.user.username}'

wish_module/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from cart_module.models import CartModel, CartDetailModel
from product_module.models import ProductModel
from wish_module.models import WishModel, WishDetailModel


# Create your views here.
class WishView(View):
    def get(self, request):
        user = request.user
        wish = WishModel.objects.filter(user_id=user.id).first()
        return render(request, 'wishlist.html', {
            'wish': wish,
        })

def add_to_wish(request):
    if request.user.is_authenticated:
        user = request.user
    else:
        return JsonResponse({'status': "not_login"})
    try:
        product_id = int(request.GET.get("product_id"))
    except:
        return JsonResponse({'status': "error"})

    product = ProductModel.objects.filter(id=product_id).first()
    if not product:
        return JsonResponse({'status': "error"})

    wish, _ = WishModel.objects.get_or_create(user_id=user.id)
    detail = WishDetailModel.objects.filter(wish_id=wish.id, product_id=product_id).first()
    if detail is not None:
        detail.save()
    else:
        detail = WishDetailModel(wish_id=wish.id, product_id=product_id)
        detail.save()
    return JsonResponse({'status': "ok"})

@login_required
def delete_wish_detail(request):
    try:
        product_id = int(request.GET.get("detail_id"))
    except ValueError:
        return JsonResponse({'status': "error", 'message': "Invalid product_id"})
    detail = WishDetailModel.objects.filter(product_id=product_id, wish__user_id=request.user.id).first()
    if not detail:
        return JsonResponse({'status': "error", 'message': "Product not found"})
    detail.delete()
    wish = WishModel.objects.filter(user_id=request.user.id).first()
    updated_wish_list = WishDetailModel.objects.filter(wish=wish)
    return render(request, 'content-wishlist.html', {
        'wish': wish,
        'wish_details': updated_wish_list  # اطمینان از ارسال لیست به‌روزشده به قالب
    })

wish_module/templates/content-wishlist.html
{% load poll_extras %}

{% if wish.wishdetailmodel_set.all %}
    <main class="main-wrapper">

        <!-- Start Wishlist Area  -->
        <div class="axil-wishlist-area axil-section-gap">
            <div class="container">
                <div class="product-table-heading">
                    <h4 class="title">لیست علاقه مندی ها</h4>
                </div>
                <div class="table-responsive">
                    <table class="table axil-product-table axil-wishlist-table">
                        <thead>
                        <tr>
                            <th scope="col" class="product-remove"></th>
                            <th scope="col" class="product-thumbnail">محصول</th>
                            <th scope="col" class="product-title"></th>
                            <th scope="col" class="product-price"> قیمت</th>
                            <th scope="col" class="product-stock-status">موجود</th>
                            <th scope="col" class="product-add-cart"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for detail in wish.wishdetailmodel_set.all %}
                            <tr>
                                <td class="product-remove"><a onclick="delete_wish_detail({{ detail.product.id }})"
                                                              class="remove-wishlist"><i
                                        class="fal fa-times"></i></a>
                                </td>
                                <td class="product-thumbnail"><a
                                        style="max-width: 100%; max-height: 150px; object-fit: contain; display: flex; justify-content: center; align-items: center;"
                                        href="{% url 'product_detail' detail.product.slug %}"><img
                                        style="max-width: 100%; max-height: 150px; object-fit: contain; display: flex; justify-content: center; align-items: center;"
                                        src="{{ detail.product.mainimage.url }}" alt="Digital Product"></a></td>
                                <td class="product-title"><a
                                        href="{% url 'product_detail' detail.product.slug %}">{{ detail.product.title }}</a>
                                </td>
                                {% if detail.product.price and detail.product.count %}
                                    <td class="product-price" data-title="Price">{{ detail.product.final_price|digits }}<span
                                            class="currency-symbol">تومان</span>
                                    </td>
                                {% elif detail.product.count and detail.product.price is None %}
                                    <td class="product-price" data-title="Price"><span
                                            class="currency-symbol">رایگان</span>
                                    </td>
                                {% else %}
                                    <td class="product-price" data-title="Price"><span
                                            class="currency-symbol">ناموجود</span>
                                    </td>
                                {% endif %}
                                {% if detail.product.count %}
                                    {% if request.user.is_authenticated %}
                                        <td class="product-stock-status" data-title="Status">موجود در انبار</td>
                                        <td class="product-add-cart"><a onclick="add_to_cart({{ detail.id }})" href="#"
                                                                        class="axil-btn btn-outline">اضافه
                                            به
                                            سبد خرید</a></td>
                                    {% else %}
                                        <td class="product-stock-status" data-title="Status">موجود در انبار</td>
                                        <td class="product-add-cart"><a onclick="add_to_cart({{ detail.id }})"
                                                                        href="{% url 'login' %}"
                                                                        class="axil-btn btn-outline">اضافه
                                            به
                                            سبد خرید</a></td>
                                    {% endif %}
                                {% else %}
                                    <td class="product-stock-status" data-title="Status">عدم موجودی</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End Wishlist Area  -->
    </main>
    <div class="service-area">
        <div class="container">
            <div class="row row-cols-xl-4 row-cols-sm-2 row-cols-1 row--20">
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="/static/images/icons/service1.png" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">ارسال سریع و ایمن</h6>
                            <p>برای تمامی سفارشات.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="/static/images/icons/service2.png" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">گارانتی بازگشت وجه</h6>
                            <p>حتی بیشتر از 7 روز.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="/static/images/icons/service3.png" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">مرجوعی طی 24 ساعت</h6>
                            <p>بدون سوال.</p>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="service-box service-style-2">
                        <div class="icon">
                            <img src="/static/images/icons/service4.png" alt="Service">
                        </div>
                        <div class="content">
                            <h6 class="title">پشتیبانی کامل</h6>
                            <p>24/7 پشتیبان آنلاین است.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="alert alert-danger text-center" style="width: 50%;margin: 70px auto">لیست علاقه مندی ها خالی است</div>
{% endif %}

wish_module/templates/wishlist.html
{% extends 'layout2.html' %}
{% load poll_extras %}
{% block title %}
    علاقه مندی ها
{% endblock %}

{% block content %}
    {% if wish.wishdetailmodel_set.all %}
        <div id="bas">
            {% include 'content-wishlist.html' %}
        </div>
    {% else %}
        <div class="alert alert-danger text-center" style="width: 50%;margin: 70px auto">لیست علاقه مندی ها خالی است</div>
    {% endif %}
{% endblock %}
{% block scripts %}
    <script src="/static/js/vendor/basket.js"></script>
    <script src="/static/js/vendor/product_detail.js"></script>
{% endblock %}